In [40]:
import numpy as np

In [41]:
arr1=np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
arr2=np.array([[2,3,4],[4,5,7],[7,8,9]])
arr2

array([[2, 3, 4],
       [4, 5, 7],
       [7, 8, 9]])

In [43]:
arr3=np.zeros(5)
arr3
arr3.dtype


dtype('float64')

In [44]:
arr3.dtype=np.int64
arr3

array([0, 0, 0, 0, 0])

In [45]:
arr4=np.array([[1,2,3],[4,5,6],[2,4,6],[4,8,9]])
print(arr4.dtype,arr4)
arr4.shape

int64 [[1 2 3]
 [4 5 6]
 [2 4 6]
 [4 8 9]]


(4, 3)

In [46]:
arr5=np.swapaxes(arr4,0,1)
arr5

array([[1, 4, 2, 4],
       [2, 5, 4, 8],
       [3, 6, 6, 9]])

In [47]:
arr4.max()

np.int64(9)

In [48]:
arr4.reshape(4,3)

array([[1, 2, 3],
       [4, 5, 6],
       [2, 4, 6],
       [4, 8, 9]])

In [51]:
arr4.sort(axis=1)
arr4

array([[1, 2, 3],
       [2, 4, 6],
       [4, 5, 6],
       [4, 8, 9]])

In [53]:
arr4=np.linspace(0,10,5)
arr4

array([ 0. ,  2.5,  5. ,  7.5, 10. ])