In [ ]:
import numpy as np


In [4]:
arr1 = np.array([2,5,6,8,9,5,5])
arr1

array([2, 5, 6, 8, 9, 5, 5])

In [59]:
# argmax: Returns the index of the maximum value
max_index = arr1.argmax()
max_index

np.int64(0)

In [60]:
# argmin: Returns the index of the minimum value
min_index = arr1.argmin()
min_index

np.int64(0)

In [61]:
# linspace: Creates an array of evenly spaced numbers
lin_arr = np.linspace(0, 10, 5)  # 5 numbers from 0 to 10
lin_arr

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [5]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
arr1.dtype

dtype('int64')

In [9]:
arr2.dtype

dtype('int64')

In [10]:
arr1.shape

(7,)

In [ ]:
arr2.shape # Shape array 2

(3, 3)

In [ ]:
arr1.ndim #Dimensions of arr1

1

In [13]:
arr2.ndim

2

In [19]:
arr3 = np.arange(1,10)
arr3

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr3.reshape(3,3) # Reshape arr3 to 3x3 matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
arr4 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr4.max() # Maximum of arr4

np.int64(9)

In [ ]:
arr4.min() #minimum of arr4

np.int64(1)

In [ ]:
arr5 = np.array([[10,20,30],[40,50,60,],[70,80,90]]) # creting a 2D array list
arr5

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
arr5.max() # Maximum of arr5

np.int64(90)

In [ ]:
arr5.min() # Minimum of arr5

np.int64(10)

In [ ]:
B = arr4+arr5 # Element wise addition
B

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [ ]:
B = arr4 - arr5 ## Element wise Substraction
B

array([[ -9, -18, -27],
       [-36, -45, -54],
       [-63, -72, -81]])

In [ ]:
B = arr4 * arr5  # Element wise multiplication
B

array([[ 10,  40,  90],
       [160, 250, 360],
       [490, 640, 810]])

In [ ]:
Square = arr4 ** 2 # Element wise Square
Square

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [ ]:
Division = arr4 / arr4 
Division

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])